services:
  telegram-gpt:
    build: .
    container_name: telegram-gpt
    restart: unless-stopped
    environment:
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      TELEGRAM_GPT_OPENAI_API_KEY: ${TELEGRAM_GPT_OPENAI_API_KEY}
      TELEGRAM_GPT_TELEGRAM_TOKEN: ${TELEGRAM_GPT_TELEGRAM_TOKEN}
      FAST_WHISPER_API_BASE_URL: ${FAST_WHISPER_API_BASE_URL}
      FAST_WHISPER_API_KEY: ${FAST_WHISPER_API_KEY}
      FAST_WHISPER_API_MODEL: ${FAST_WHISPER_API_MODEL}
      TTS_BASE_URL: ${TTS_BASE_URL}
      TTS_API_KEY: ${TTS_API_KEY}
      TTS_MODEL: ${TTS_MODEL}
      TTS_VOICE: ${TTS_VOICE}
      TTS_BACKEND: ${TTS_BACKEND}
      LANGUAGE: ${LANGUAGE}