# For more details, read this: https://coolify.io/docs/github-actions
name: Build Docker Image
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      platform:
        description: Specify the platform supported
        default: 'linux/arm64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'limcheekin/telegram-gpt'

jobs:
  build:
    runs-on: ${{ github.event.inputs.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Show Runner
        run: |
          echo "Running on runner: $(uname -a)"
          echo "Platform input: ${{ github.event.inputs.platform }}"

      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN  }}
      - name: Replace slash with dash
        id: replace_slash
        run: |
          platform_value="${{ github.event.inputs.platform }}"
          replaced_value="${platform_value//\//-}"
          echo "REPLACED_PLATFORM=$replaced_value" >> $GITHUB_ENV
      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ env.REPLACED_PLATFORM }}:latest
