# For more details, read this: https://coolify.io/docs/github-actions
name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        description: Specify the platform supported
        default: 'linux/amd64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'limcheekin/telegram-gpt'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN  }}
      - name: Replace slash with dash
        id: replace_slash
        run: |
          platform_value="${{ github.event.inputs.platform }}"
          replaced_value="${platform_value//\//-}"
          echo "::set-output name=replaced_platform::$replaced_value"
      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ steps.replace_slash.outputs.replaced_platform }}:latest
