# For more details, read this: https://coolify.io/docs/github-actions
name: Deploy to Coolify DEV
on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      platform: 'linux/arm64'
    secrets:
      TOKEN: ${{ secrets.TOKEN }}    
  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to Coolify
  #      run: | 
  #        curl --request GET '${{ secrets.COOLIFY_WEBHOOK_DEV }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN_DEV }}'
